[platformio]
default_envs = controller

auto_clean = true

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio

[env:controller]
board = esp32dev
build_src_filter =
    +<firmware/controller>
    +<firmware/common>

[env:display]
board = esp32dev
build_src_filter =
    +<firmware/display>
    +<firmware/common>

[env:buzzer]
board = esp32dev
build_src_filter =
    +<firmware/buzzer>
    +<firmware/common>

[env:native]
platform = native
build_src_filter =
    +<firmware/common>
